#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

base_path = File.expand_path("../lib", __dir__)

if File.exist?(base_path)
  require_relative "../lib/bump_version"
else
  require "bump_version"
end

args = ARGV

BumpVersion::CLI.start(args, debug: false)
